### ISSUE TITLE
SIGABRT on macOS 14.1 / setproctitle 1.3.3

### ISSUE THREAD

**Issue by ekolve** [dvarrazzo/py-setproctitle#138] opened 2023-11-03 02:57 UTC
Running the following on MacOS 14.1 MacBook Pro M1 with Python 3.11.6 with setproctitle 1.3.3:

```python
#!/usr/bin/env python
import multiprocessing as mp
def child():
    from setproctitle import setproctitle
    setproctitle('title in child')

if __name__ == '__main__':
    import numpy
    mp.set_start_method('fork')
    p = mp.Process(target=child)]
    p.start()
    p.join()
    print(p.exitcode) # returns -6 on failure 0 on success
```

Results in the following error:
```
objc[98626]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[98626]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
-6
```

Here are a few interesting details about this:
* If I downgrade setproctitle to 1.2.3, the error goes away
* if I remove the numpy import the error goes away
* if I just set OPENBLAS_NUM_THREADS=1 (leaving numpy and setproctitle==1.3.3), the error goes away

**Comment by gershnik** [comment] 2023-11-03 05:03
Thank you for reporting!

From https://docs.python.org/3/library/multiprocessing.html

> The fork start method should be considered unsafe as it can lead to crashes of the subprocess.

See also #133 and issues linked from there for more details.

**Comment by dvarrazzo** [comment] 2023-11-03 09:46
Thank you @gershnik 

Closing it as duplicate of the above issues. Unfortunately, as hard as we tried to work around it, the problem is intrinsic in the fork on macOS.

**Closed by dvarrazzo** 2023-11-03 09:46 UTC
