### ISSUE TITLE
setproctitle does not change title of process on mac os

### ISSUE THREAD

**Issue by jacob-lee** [dvarrazzo/py-setproctitle#128] opened 2023-02-06 19:58 UTC
OS: macOS Ventura 13.0.1
Processor: M1 Max
python: 3.10.9 (provided by conda)
setproctitle: >v1.2.3

Issue: Custom set process name appears to be ignored. It is neither visible using _ps_ nor using _Activity Monitor_ on MacOS.  I'm expecting to see something like `gunicorn: worker [my custom name]` but instead I see `/path/to/my/python /path/to/python/script.py` More importantly for me, its not showing up to my psutil code I use to manage the process.

The problem appears to be specific to Mac as the same code behaves correctly on Linux.

Downgrading to setproctitle to v1.2.3 *fixes* the issue when using _ps_ and in my own code (though it does not show up as anything other than `python` in _Activity Monitor_). I suspect that maybe this has to do with the changes made to address issue #10.

**Comment by gershnik** [comment] 2023-02-06 22:14
@jacob-lee Thank you for reporting this! 
Which Python distribution are you using? Are you on Intel or Arm Mac? Does the issue reproduce with this simple script?
```python
import setproctitle
import time

setproctitle.setproctitle("Test")
time.sleep(1000)
```

FWIW I am on macOS 13.2, Intel and everything works fine for me with python.org  Python 3.10.4.

**Comment by jacob-lee** [comment] 2023-02-06 22:26
Yeah, I'm on Apple Silicon. I'm using conda, 23.1.0.

Running your script, with setproctitle version 1.3.2 I get this output from _ps_

```
14244 ttys002    0:00.03 python testscript.py
```

Switching down to 1.2.3 I get this output:

```
14442 ttys002    0:00.03 Test 
```

**Comment by gershnik** [comment] 2023-02-06 22:43
Thank you!.
This is quite strange. Even if the Process Monitor stuff fails the code still should _also_  execute the same logic as 1.2.3 did...
I'll try to set up your environment and check what's going on there.

**Comment by gershnik** [comment] 2023-02-06 22:49
@jacob-lee  Actually, I've just realized something. Another difference between the current version and 1.2.3 not quite related to #10 is that it will do silently nothing if native code is not available at all. Is this perhaps the case that pip3 cannot get the native library for your setup? I am not familiar with conda but do you get any warnings when installing it and do you actually have something like setproctitle_xxx.so (not sure what the exact name would be under conda) in your site-packages/setproctitle?

**Comment by gershnik** [comment] 2023-02-06 22:55
@jacob-lee Also can you set SPT_DEBUG=1 environment variable prior to running the sample code above? It should provide more info on what exactly is failing.

**Comment by jacob-lee** [comment] 2023-02-07 00:03
I have this file:

```
./lib/python3.10/site-packages/setproctitle.cpython-310-darwin.so
```

However, this is the output with SPT_DEBUG=1:

```
DEBUG:setproctitle:failed to import setproctitle: dlopen(/Users/jacoblee/miniconda3/envs/spockturk-test/lib/python3.10/site-packages/setproctitle/_setproctitle.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '___CFConstantStringClassReference'
DEBUG:setproctitle:setproctitle C module not available
DEBUG:setproctitle:setproctitle C module not available
```

**Comment by gershnik** [comment] 2023-02-07 00:26
Very helpful, thank you! From quick googling this error - "symbol not found in flat namespace '___CFConstantStringClassReference'" - happens (including with psutil of all things!) when the shared library is corrupt for some reason. That is, some issue with package install.
What is the size of `/Users/jacoblee/miniconda3/envs/spockturk-test/lib/python3.10/site-packages/setproctitle/_setproctitle.cpython-310-darwin.so` Also what does 
```bash
file /Users/jacoblee/miniconda3/envs/spockturk-test/lib/python3.10/site-packages/setproctitle/_setproctitle.cpython-310-darwin.so
```
report? 
Also if you happen to have a command line tool called `otool` on your machine (its part of Apple dev tools so not available by default) what does
```bash
otool -L /Users/jacoblee/miniconda3/envs/spockturk-test/lib/python3.10/site-packages/setproctitle/_setproctitle.cpython-310-darwin.so
```
say?

**Comment by jacob-lee** [comment] 2023-02-07 00:33
The file is 119K.

Here is the output from those two commands:

```
file _setproctitle.cpython-310-darwin.so 
_setproctitle.cpython-310-darwin.so: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64] [arm64:Mach-O 64-bit bundle arm64]
_setproctitle.cpython-310-darwin.so (for architecture x86_64):	Mach-O 64-bit bundle x86_64
_setproctitle.cpython-310-darwin.so (for architecture arm64):	Mach-O 64-bit bundle arm64
```

```
otool -L _setproctitle.cpython-310-darwin.so 
_setproctitle.cpython-310-darwin.so (architecture x86_64):
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
_setproctitle.cpython-310-darwin.so (architecture arm64):
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```

**Comment by gershnik** [comment] 2023-02-07 00:54
This is very strange. At least superficially it looks like a valid file. If you don't mind, could you zip the .so file and attach it here?

**Comment by jacob-lee** [comment] 2023-02-07 00:57
Not sure how to upload here. But here is the file:

https://drive.google.com/file/d/14Yh4JO1Ti-k2NYquao7VxwIa-xxTzI8Q/view?usp=sharing

**Comment by gershnik** [comment] 2023-02-07 01:07
I've got it, thank you! Surprisingly, your library works just fine on my machine with regular Python. :( 
Also it does have ARM architecture so that shouldn't be an issue.
Let me research this a bit and see if I can find anything. This is very strange.

**Comment by gershnik** [comment] 2023-02-07 01:28
So from googling various variations of the error message it appears that this might be something caused by mixup of binaries under Anaconda. Unfortunately my knowledge of Anaconda is essentially 0
One person claims that doing something like
```bash
pip3 uninstall setproctitle
conda install setproctitle
```
might help. Other people talk about not "mixing channels", whatever it is, and refer to this: https://stackoverflow.com/questions/66354697/conda-3-9-is-not-working-with-numpy-on-macos-reason-image-not-found/66356877#66356877 as an explanation

Beyond this I don't really have any idea of what might help here. It seems clear that the issue is environmental though rather than something in setproctitle itself.

**Comment by dvarrazzo** [comment] 2023-02-07 01:36
This can be closed as Conda problem.

**Closed by dvarrazzo** 2023-02-07 01:36 UTC

**Comment by jacob-lee** [comment] 2023-02-07 06:43
I can verify that using the base system python and venv on my Mac resolves the issue. Surprising, tbh; never have had this kind of issue before while using conda in this way. Thank you for looking into it.
