### ISSUE TITLE
Setting title fails sometimes

### ISSUE THREAD

**Issue by RenaKunisaki** [dvarrazzo/py-setproctitle#57] opened 2018-11-02 20:59 UTC
This works:

```python
import setproctitle
title = setproctitle.getproctitle()
log.debug("current title: %s", title)
setproctitle.setproctitle("filedb web server - " + str(title))
```

If we change the hyphen to a colon, it doesn't work (the title remains unchanged):

```python
import setproctitle
title = setproctitle.getproctitle()
log.debug("current title: %s", title)
setproctitle.setproctitle("filedb web server: " + str(title))
```

Version: Python 3.7.0 (default, Sep 15 2018, 19:13:07) [GCC 8.2.1 20180831] on linux  
Running on Arch AMD64

**Comment by dvarrazzo** [comment] 2020-06-11 12:54
I can't reproduce this: it works well for me.

I know a long time is passed, but if you want to work on it I may need more details. Otherwise I'll close it there.

**Closed by dvarrazzo** 2020-06-11 12:54 UTC
